name: Top GitHub Users

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Run Top GitHub Users Action
        uses: gayanvoice/top-github-users-action@main
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
